window.addEventListener('youssef-auth-ready',async(e)=>{
  const P=window.YoussefAlaaPlatform,u=e.detail?.appUser;if(!P||!u||u.role!=='student')return;
  const params=new URLSearchParams(location.search), lessonId=params.get('lessonId'), courseId=params.get('courseId');
  const main=document.querySelector('main'); if(!main)return;
  const wrap=document.createElement('section'); wrap.className='platform-panel'; wrap.style='max-width:1400px;margin:18px auto;padding:18px 20px'; wrap.innerHTML='<div class="platform-empty">جارٍ تحميل الدرس...</div>'; main.prepend(wrap);
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); const fmt=n=>new Intl.NumberFormat('ar-EG').format(Number(n||0));
  try{
    let lessons=[];
    if(lessonId){const s=await P.getDoc(P.doc(P.db,'lessons',lessonId));if(s.exists())lessons=[{id:s.id,...s.data()}]} else if(courseId){const s=await P.getDocs(P.query(P.collection(P.db,'lessons'),P.where('courseId','==',courseId)));lessons=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.published!==false).sort((a,b)=>Number(a.order||0)-Number(b.order||0));}
    if(!lessons.length){wrap.innerHTML='<div class="platform-empty">لا توجد دروس متاحة لهذا الكورس.</div>';return;}
    const lesson=lessons[0];let allowed=true;try{if(lesson.courseId){const en=await P.getDoc(P.doc(P.db,'enrollments',`${P.auth.currentUser.uid}_${lesson.courseId}`));const direct=await P.getDoc(P.doc(P.db,'lessonAccess',`${P.auth.currentUser.uid}_${lesson.id}`));allowed=en.exists()||direct.exists()}}catch(_){ }if(!allowed){wrap.innerHTML='<div class="platform-empty">هذا المحتوى غير مفعّل على حسابك.</div>';return;}const progressRef=P.doc(P.db,'lessonProgress',`${P.auth.currentUser.uid}_${lesson.id}`);let progressSnap=await P.getDoc(progressRef);let prog=progressSnap.exists()?progressSnap.data():{};const source=lesson.mediaUrl||'';
    const player=lesson.mediaType==='video'?`<div class="video-frame"><video id="lesson-video" playsinline controls preload="metadata" src="${esc(source)}"></video></div>`:`<div class="app-notice">هذا الدرس عبارة عن ${esc(lesson.mediaType||'ملف')}. <a target="_blank" rel="noopener" href="${esc(source)}">فتح المحتوى</a></div>`;
    wrap.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap"><div><span class="platform-badge success">متاح</span><h2>${esc(lesson.title)}</h2><p style="color:#5b6072">${esc(lesson.description||'')}</p></div><div><span class="platform-badge">الدرس ${fmt(lesson.order||1)}</span></div></div><div style="position:relative">${player}<div id="video-watermark" style="position:absolute;top:18%;right:8%;padding:4px 8px;border-radius:8px;background:rgba(0,0,0,.28);color:rgba(255,255,255,.72);font-size:11px;pointer-events:none;user-select:none;animation:ysaWm 23s linear infinite">${esc(u.displayName||'طالب')} • ${esc(u.studentPhone||'')}</div></div><div class="platform-actions" style="margin-top:10px"><label class="platform-label" style="margin:0;display:flex;align-items:center;gap:8px">سرعة التشغيل<select id="video-speed" class="platform-select" style="width:auto"><option value="0.5">0.5x</option><option value="1" selected>1x</option><option value="1.25">1.25x</option><option value="1.5">1.5x</option><option value="2">2x</option></select></label></div><div style="margin-top:12px"><div style="display:flex;justify-content:space-between;font-size:12px;color:#5b6072"><span>التقدم المحفوظ</span><span id="watch-percent">${fmt(Math.round(Number(prog.watchPercent||0)))}%</span></div><div class="progress-track"><span id="watch-bar" style="width:${Math.min(100,Number(prog.watchPercent||0))}%"></span></div></div>${Array.isArray(lesson.chapters)&&lesson.chapters.length?`<div class="platform-panel" style="margin-top:14px"><b>الفصول</b><div class="platform-actions" style="margin-top:8px">${lesson.chapters.map((c,i)=>`<button class="platform-btn" data-chapter="${i}">${esc(c.title||('فصل '+(i+1)))}</button>`).join('')}</div></div>`:''}<div class="platform-panel" style="margin-top:14px"><h3>ملاحظاتك أثناء الدرس</h3><textarea id="lesson-note" class="platform-textarea" rows=3 placeholder="اكتب ملاحظة مرتبطة بالوقت الحالي..."></textarea><div class="platform-actions" style="margin-top:8px"><button id="save-lesson-note" class="platform-btn primary">حفظ الملاحظة</button><span id="note-status" style="color:#5b6072"></span></div><div id="lesson-notes-list" style="margin-top:10px"></div></div><div class="platform-actions" style="margin-top:14px"><a class="platform-btn" href="${courseId?`/lesson.html?courseId=${encodeURIComponent(courseId)}`:'/student-dashboard.html'}">رجوع</a>${lesson.nextLessonId?`<a class="platform-btn primary" id="next-lesson" href="/lesson.html?lessonId=${encodeURIComponent(lesson.nextLessonId)}">الدرس التالي</a>`:''}</div>`;
    const video=document.querySelector('#lesson-video');
    if(video){let maxWatched=Number(prog.maxWatchedSeconds||0);video.addEventListener('loadedmetadata',()=>{if(Number(prog.lastPosition||0)<video.duration)video.currentTime=Number(prog.lastPosition||0)});video.addEventListener('timeupdate',async()=>{if(video.currentTime>maxWatched+2)maxWatched=video.currentTime;const percent=video.duration?Math.min(100,maxWatched/video.duration*100):0;document.querySelector('#watch-percent').textContent=Math.round(percent)+'%';document.querySelector('#watch-bar').style.width=percent+'%';if(Math.floor(video.currentTime)%10===0){await P.setDoc(progressRef,{uid:P.auth.currentUser.uid,lessonId:lesson.id,courseId:lesson.courseId||courseId,lastPosition:video.currentTime,maxWatchedSeconds:maxWatched,watchPercent:percent,updatedAt:P.serverTimestamp()},{merge:true})}});video.addEventListener('seeking',()=>{if(video.currentTime>maxWatched+3)video.currentTime=maxWatched});
      document.querySelector('#video-speed')?.addEventListener('change',ev=>{video.playbackRate=Number(ev.target.value)});document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{const c=lesson.chapters?.[Number(b.dataset.chapter)];if(c?.time!=null)video.currentTime=Number(c.time)});
      const noteForm=document.querySelector('#save-lesson-note');noteForm?.addEventListener('click',async()=>{const txt=document.querySelector('#lesson-note').value.trim();if(!txt)return;try{await P.addDoc(P.collection(P.db,'lessonNotes'),{uid:P.auth.currentUser.uid,lessonId:lesson.id,courseId:lesson.courseId||courseId,text:txt,timeSeconds:video.currentTime||0,createdAt:P.serverTimestamp()});document.querySelector('#lesson-note').value='';document.querySelector('#note-status').textContent='تم حفظ الملاحظة';loadNotes()}catch(err){P.messageBox(err.message)}});const loadNotes=async()=>{const s=await P.getDocs(P.query(P.collection(P.db,'lessonNotes'),P.where('uid','==',P.auth.currentUser.uid),P.limit(50)));const rs=s.docs.map(d=>d.data()).filter(x=>x.lessonId===lesson.id).sort((a,b)=>(b.timeSeconds||0)-(a.timeSeconds||0));document.querySelector('#lesson-notes-list').innerHTML=rs.map(x=>`<div class="app-notice" style="margin-top:6px"><b>${Math.floor((x.timeSeconds||0)/60)}:${String(Math.floor((x.timeSeconds||0)%60)).padStart(2,'0')}</b> — ${esc(x.text)}</div>`).join('')||''};loadNotes();
      document.querySelector('#next-lesson')?.addEventListener('click',async(ev)=>{if(Number(document.querySelector('#watch-percent').textContent.replace('%',''))<33){ev.preventDefault();P.messageBox('لا يمكن فتح الدرس التالي قبل مشاهدة ثلث الدرس على الأقل.');}});
    }
  }catch(err){wrap.innerHTML=`<div class="platform-empty">تعذر تحميل الدرس: ${esc(err.message)}</div>`}
});
