window.addEventListener('youssef-auth-ready', async (event) => {
  const { appUser } = event.detail || {};
  if (!appUser || !['teacher','ta','admin','owner'].includes(appUser.role)) return;
  const P=window.YoussefAlaaPlatform; if(!P)return;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const fmt=n=>new Intl.NumberFormat('ar-EG').format(Number(n||0));
  const date=d=>d?.toDate?d.toDate().toLocaleString('ar-EG'):(d?new Date(d).toLocaleString('ar-EG'):'—');
  const ownOnly=appUser.role==='teacher'||appUser.role==='ta';
  async function getOwn(name, field='teacherId'){
    const q=P.query(P.collection(P.db,name),P.where(field,'==',P.auth.currentUser.uid));
    const s=await P.getDocs(q); return s.docs.map(d=>({id:d.id,...d.data()}));
  }
  async function loadCourses(){const box=$('#teacher-courses-body');if(!box)return;try{const rows=await getOwn('courses');box.innerHTML=rows.map(c=>`<tr><td>${esc(c.title)}</td><td>${esc(c.grade||'—')}</td><td>${fmt(c.price)} ج.م</td><td>${c.published?'<span class="platform-badge success">منشور</span>':'<span class="platform-badge warn">مراجعة الإدارة</span>'}</td><td>${date(c.createdAt)}</td></tr>`).join('')||`<tr><td colspan="5" class="platform-empty">أنشئ أول كورس لك.</td></tr>`}catch(e){box.innerHTML='<tr><td colspan="5" class="platform-empty">تعذر تحميل الكورسات.</td></tr>'}}
  async function createCourse(){const f=$('#course-form');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const data={title:$('#course-title').value.trim(),description:$('#course-description').value.trim(),grade:$('#course-grade').value,track:$('#course-track').value.trim(),subject:$('#course-subject').value.trim(),price:Number($('#course-price').value||0),teacherId:P.auth.currentUser.uid,teacherName:appUser.displayName||'',published:false,status:'pending',createdAt:P.serverTimestamp(),updatedAt:P.serverTimestamp()};if(!data.title)return P.messageBox('اكتب اسم الكورس.');try{await P.addDoc(P.collection(P.db,'courses'),data);P.messageBox('تم إنشاء الكورس وإرساله للمراجعة قبل النشر.','success');f.reset();loadCourses()}catch(err){P.messageBox(err.message||'تعذر إنشاء الكورس.')}})}
  async function createQuestion(){const f=$('#question-form');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const type=$('#q-type').value;let options=[];try{options=JSON.parse($('#q-options').value||'[]')}catch{ return P.messageBox('خيارات السؤال يجب أن تكون JSON صحيحة مثل ["أ", "ب", "ج"].') } const data={examId:$('#q-exam').value.trim(),type,text:$('#q-text').value.trim(),options,correctAnswer:$('#q-correct').value.trim(),points:Number($('#q-points').value||1),teacherId:P.auth.currentUser.uid,published:false,status:'pending',createdAt:P.serverTimestamp(),updatedAt:P.serverTimestamp()};if(!data.examId||!data.text)return P.messageBox('أكمل الامتحان ونص السؤال.');try{await P.addDoc(P.collection(P.db,'questions'),data);P.messageBox('تم حفظ السؤال.','success');f.reset();loadQuestions()}catch(err){P.messageBox(err.message)}})}
  async function createExam(){const f=$('#exam-form');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const data={title:$('#exam-title').value.trim(),courseId:$('#exam-course').value.trim(),durationMinutes:Number($('#exam-duration').value||30),attemptsAllowed:Number($('#exam-attempts').value||3),questionCount:Number($('#exam-count').value||20),passScore:Number($('#exam-pass').value||50),scorePolicy:$('#exam-policy').value,allowBackNavigation:$('#exam-back').value==='true',showAnswersAfterSubmit:$('#exam-show').value==='true',isSurprise:$('#exam-surprise').value==='true',randomizeQuestions:true,randomizeOptions:true,published:false,teacherId:P.auth.currentUser.uid,createdAt:P.serverTimestamp(),updatedAt:P.serverTimestamp()};if(!data.title)return P.messageBox('اكتب اسم الامتحان.');try{await P.addDoc(P.collection(P.db,'exams'),data);P.messageBox('تم إنشاء الامتحان. اطلب من الإدارة نشره.','success');f.reset();loadExams()}catch(err){P.messageBox(err.message)}})}
  async function loadExams(){const box=$('#exams-body');if(!box)return;try{const rows=await getOwn('exams');box.innerHTML=rows.map(x=>`<tr><td>${esc(x.title)}</td><td>${x.durationMinutes} دقيقة</td><td>${x.attemptsAllowed}</td><td>${x.passScore}%</td><td>${x.published?'<span class="platform-badge success">منشور</span>':'<span class="platform-badge warn">غير منشور</span>'}</td></tr>`).join('')||`<tr><td colspan="5" class="platform-empty">لا توجد امتحانات.</td></tr>`;const sel=$('#q-exam');if(sel){sel.innerHTML='<option value="">اختر الامتحان</option>'+rows.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}}catch(e){box.innerHTML='<tr><td colspan="5" class="platform-empty">تعذر تحميل الامتحانات.</td></tr>'}}
  async function loadQuestions(){const box=$('#questions-body');if(!box)return;try{const rows=await getOwn('questions');box.innerHTML=rows.map(x=>`<tr><td>${esc(x.examId)}</td><td>${esc(x.type)}</td><td>${esc(x.text).slice(0,110)}</td><td>${fmt(x.points)}</td><td>${date(x.createdAt)}</td></tr>`).join('')||`<tr><td colspan="5" class="platform-empty">لا توجد أسئلة.</td></tr>`}catch(e){box.innerHTML='<tr><td colspan="5" class="platform-empty">تعذر تحميل الأسئلة.</td></tr>'}}
  async function loadStudents(){const box=$('#teacher-students-body');if(!box)return;try{const en=await getOwn('enrollments');const ids=[...new Set(en.map(x=>x.studentUid).filter(Boolean))];if(!ids.length){box.innerHTML='<tr><td colspan="5" class="platform-empty">لا يوجد طلاب مرتبطون بعد.</td></tr>';return}const rows=[];for(const id of ids){try{const u=await P.getDoc(P.doc(P.db,'users',id));if(u.exists())rows.push({id,...u.data()})}catch{}}box.innerHTML=rows.map(x=>`<tr><td>${esc(x.displayName)}</td><td>${esc(x.grade||'—')}</td><td>${esc(x.track||'—')}</td><td>${esc(x.studentPhone||'—')}</td><td>${esc(x.status||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="platform-empty">لم نجد بيانات الطلاب.</td></tr>'}catch(e){box.innerHTML='<tr><td colspan="5" class="platform-empty">تعذر تحميل الطلاب.</td></tr>'}}
  async function loadWallet(){const bal=$('#wallet-balance');if(!bal)return;try{const tx=await getOwn('transactions');const wd=await getOwn('withdrawalRequests');const total=tx.filter(x=>x.type==='sale').reduce((a,x)=>a+Number(x.netAmount??x.amount??0),0);const withdrawn=wd.filter(x=>x.status==='approved').reduce((a,x)=>a+Number(x.amount||0),0);bal.textContent=fmt(Math.max(0,total-withdrawn))+' ج.م';$('#wallet-sales').textContent=fmt(tx.filter(x=>x.type==='sale').reduce((a,x)=>a+Number(x.amount||0),0));$('#wallet-commission').textContent=fmt(tx.filter(x=>x.type==='commission').reduce((a,x)=>a+Number(x.amount||0),0));$('#wallet-withdrawn').textContent=fmt(withdrawn);$('#wallet-pending')&&($('#wallet-pending').textContent=fmt(wd.filter(x=>x.status==='pending').reduce((a,x)=>a+Number(x.amount||0),0)));const body=$('#wallet-tx');if(body)body.innerHTML=tx.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,30).map(x=>`<tr><td>${esc(x.type)}</td><td>${fmt(x.amount)} ج.م</td><td>${fmt(x.netAmount)} ج.م</td><td>${date(x.createdAt)}</td></tr>`).join('')||'<tr><td colspan="4" class="platform-empty">لا توجد معاملات.</td></tr>'}catch(e){console.warn(e)}}
  async function requestWithdrawal(){const f=$('#withdraw-form');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const amount=Number($('#withdraw-amount').value||0);if(amount<=0)return P.messageBox('اكتب مبلغًا صحيحًا.');try{await P.addDoc(P.collection(P.db,'withdrawalRequests'),{teacherId:P.auth.currentUser.uid,teacherName:appUser.displayName||'',amount,method:$('#withdraw-method').value,account:$('#withdraw-account').value.trim(),status:'pending',createdAt:P.serverTimestamp()});P.messageBox('تم إرسال طلب السحب للإدارة.','success');f.reset();loadWallet()}catch(err){P.messageBox(err.message)}})}
  async function loadLiveStats(){try{const [c,l,e,a]=await Promise.all([getOwn('courses'),getOwn('lessons'),getOwn('enrollments') ,getOwn('examAttempts')]);document.querySelector('#td-courses')&&(document.querySelector('#td-courses').textContent=fmt(c.length));document.querySelector('#td-lessons')&&(document.querySelector('#td-lessons').textContent=fmt(l.length));document.querySelector('#td-students')&&(document.querySelector('#td-students').textContent=fmt(new Set(e.map(x=>x.studentUid)).size));document.querySelector('#td-attempts')&&(document.querySelector('#td-attempts').textContent=fmt(a.length));}catch(err){console.warn(err)}}
  await Promise.all([loadCourses(),createCourse(),loadExams(),createExam(),loadQuestions(),createQuestion(),loadStudents(),loadWallet(),requestWithdrawal(),loadLiveStats()]);
});
